#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/test
#  username: root
#  password: 123456

spring:
  profiles:
    active: sttest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456

server:
  port: 80

#日志记录级别
logging:
  level:
    cn.st: debug
    org.springframework: info
mybatis:
  # 实体类别名包路径
  type-aliases-package: cn.st.pojo
  # 映射文件路径
#  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
